// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Egor",
            "url": "http://github.com/egorkto"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/sign-up": {
            "post": {
                "description": "Создает новую учетную запись пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Регистрация нового пользователя",
                "parameters": [
                    {
                        "description": "Данные регистрации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth_transport_http.SignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Успешная регистрация",
                        "schema": {
                            "$ref": "#/definitions/internal_auth_transport_http.SignUpResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/github_com_egorkto_Chat-go_internal_echo.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Пользователь уже существует",
                        "schema": {
                            "$ref": "#/definitions/github_com_egorkto_Chat-go_internal_echo.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_egorkto_Chat-go_internal_echo.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error details"
                },
                "message": {
                    "type": "string",
                    "example": "failed to proccess request"
                }
            }
        },
        "internal_auth_transport_http.SignUpRequest": {
            "type": "object",
            "required": [
                "full_name",
                "password"
            ],
            "properties": {
                "full_name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3,
                    "example": "Иван Иванов"
                },
                "password": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 5,
                    "example": "Qwer1234?,4"
                }
            }
        },
        "internal_auth_transport_http.SignUpResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "access_token_example"
                },
                "refresh_token": {
                    "type": "string",
                    "example": "refresh_token_example"
                },
                "user": {
                    "$ref": "#/definitions/internal_auth_transport_http.UserDTO"
                }
            }
        },
        "internal_auth_transport_http.UserDTO": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string",
                    "example": "Иван Иванов"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "version": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:5845",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Chat API",
	Description:      "Chat go",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
